/**
 * CurateExecutor regression tests
 *
 * 1. Variable naming: UUID hyphens in sandbox variable names cause
 *    ReferenceError when LLM writes code using underscores.
 *
 * 2. Session-leak fix: createTaskSession must not be called before
 *    processFileReferences, so a preprocessing failure cannot leak sessions.
 */

import {expect} from 'chai'
import {restore, stub} from 'sinon'

import type {ICipherAgent} from '../../../../src/agent/core/interfaces/i-cipher-agent.js'

import {LocalSandbox} from '../../../../src/agent/infra/sandbox/local-sandbox.js'

/**
 * Mock cipher agent used by the runAgentBody / finalize split tests.
 * Hoisted to module scope (consistent-function-scoping lint rule).
 */
function buildSplitTestAgent(): ICipherAgent {
  return {
    cancel: stub().resolves(false),
    createTaskSession: stub().resolves('session-id'),
    deleteSandboxVariable: stub(),
    deleteSandboxVariableOnSession: stub(),
    deleteSession: stub().resolves(true),
    deleteTaskSession: stub().resolves(),
    execute: stub().resolves(''),
    executeOnSession: stub().resolves('curated'),
    generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
    getSessionMetadata: stub().resolves(),
    getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
    listPersistedSessions: stub().resolves([]),
    reset: stub(),
    setSandboxVariable: stub(),
    setSandboxVariableOnSession: stub(),
    start: stub().resolves(),
    stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
  } as unknown as ICipherAgent
}

import {FileValidationError} from '../../../../src/server/core/domain/errors/task-error.js'
import {FileContextTreeManifestService} from '../../../../src/server/infra/context-tree/file-context-tree-manifest-service.js'
import {FileContextTreeSnapshotService} from '../../../../src/server/infra/context-tree/file-context-tree-snapshot-service.js'
import {FileContextTreeSummaryService} from '../../../../src/server/infra/context-tree/file-context-tree-summary-service.js'
import {DreamStateService} from '../../../../src/server/infra/dream/dream-state-service.js'
import {CurateExecutor} from '../../../../src/server/infra/executor/curate-executor.js'

describe('CurateExecutor (regression)', () => {
  afterEach(() => {
    restore()
  })

  describe('sandbox variable naming', () => {
    // Typical UUID taskId with hyphens (as generated by crypto.randomUUID())
    const taskId = '8cd8e2d8-a7fc-4371-89ca-59460687c12d'
    // What the LLM would write in code-exec (hyphens → underscores, valid JS identifier)
    const llmGeneratedVarName = '__curate_meta_8cd8e2d8_a7fc_4371_89ca_59460687c12d'

    describe('bug: hyphenated taskId causes variable name mismatch', () => {
      it('should fail with ReferenceError when variable stored with hyphens but accessed with underscores', async () => {
        const sandbox = new LocalSandbox()

        // Old (buggy) behavior: store variable using raw taskId containing hyphens
        const buggyMetaVar = `__curate_meta_${taskId}` // "..._8cd8e2d8-a7fc-..."
        sandbox.updateContext({[buggyMetaVar]: {charCount: 100, lineCount: 5}})

        // LLM writes underscores in code (hyphens are not valid JS identifier chars)
        const result = await sandbox.execute(llmGeneratedVarName)

        // Variable is in sandbox as hyphen-version, but LLM looks up underscore-version → not found
        expect(result.stderr).to.include('ReferenceError')
        expect(result.stderr).to.include(llmGeneratedVarName)
      })
    })

    describe('fix: taskIdSafe with underscores eliminates mismatch', () => {
      it('should succeed when variable stored with underscores matching LLM output', async () => {
        const sandbox = new LocalSandbox()

        // Fixed behavior: replace hyphens before naming sandbox variables
        const taskIdSafe = taskId.replaceAll('-', '_')
        const fixedMetaVar = `__curate_meta_${taskIdSafe}` // all underscores
        sandbox.updateContext({[fixedMetaVar]: {charCount: 100, lineCount: 5}})

        // LLM writes underscores → now matches sandbox variable
        const result = await sandbox.execute(`${llmGeneratedVarName}.charCount`)

        expect(result.stderr).to.equal('')
        expect(result.returnValue).to.equal(100)
      })

      it('should correctly transform all UUID segments (4 hyphens replaced)', () => {
        const taskIdSafe = taskId.replaceAll('-', '_')

        expect(taskIdSafe).to.not.include('-')
        expect(taskIdSafe).to.equal('8cd8e2d8_a7fc_4371_89ca_59460687c12d')

        const metaVar = `__curate_meta_${taskIdSafe}`
        expect(metaVar).to.equal(llmGeneratedVarName)
      })
    })
  })

  describe('session-leak fix', () => {
    it('should not call createTaskSession when processFileReferences throws', async () => {
      const createTaskSession = stub().resolves('session-id')
      const deleteTaskSession = stub().resolves()

      const agent = {
        cancel: stub().resolves(false),
        createTaskSession,
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession,
        execute: stub().resolves(''),
        executeOnSession: stub().resolves(''),
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession: stub(),
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      // Pass non-existent file paths to trigger FileValidationError in processFileReferences
      const executor = new CurateExecutor()
      const options = {
        content: 'test content',
        files: ['/nonexistent/path/to/file.txt', '/another/invalid/file.md'],
        taskId: 'task-123',
      }

      try {
        await executor.executeWithAgent(agent, options)
        expect.fail('Should have thrown FileValidationError')
      } catch (error) {
        expect(error).to.be.instanceOf(FileValidationError)
      }

      // Key assertion: createTaskSession was NEVER called because
      // processFileReferences runs BEFORE createTaskSession in the restructured code.
      // Previously, createTaskSession ran first and the session would leak on throw.
      expect(createTaskSession.called).to.be.false
      expect(deleteTaskSession.called).to.be.false
    })
  })

  describe('background queue drain', () => {
    it('waits for background work before returning curate results', async () => {
      const createTaskSession = stub().resolves('session-id')
      const deleteTaskSession = stub().resolves()
      const drainBackgroundWork = stub().resolves()
      const executeOnSession = stub().resolves('curated')

      const agent = {
        cancel: stub().resolves(false),
        createTaskSession,
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession,
        drainBackgroundWork,
        execute: stub().resolves(''),
        executeOnSession,
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession: stub(),
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      const executor = new CurateExecutor()
      const response = await executor.executeWithAgent(agent, {
        clientCwd: '/workspace',
        content: 'capture auth knowledge',
        taskId: 'task-123',
      })

      expect(response).to.equal('curated')
      expect(drainBackgroundWork.calledOnce).to.be.true
      expect(deleteTaskSession.calledOnceWithExactly('session-id')).to.be.true
      expect(drainBackgroundWork.calledBefore(deleteTaskSession)).to.be.true
    })
  })

  describe('workspace scoping - projectRoot for post-processing (PR3)', () => {
    it('should use projectRoot (not worktreeRoot) as baseDir for snapshot service', async () => {
      // The curate executor uses baseDir for FileContextTreeSnapshotService,
      // summary propagation, and manifest rebuild — all of which need the
      // project root where .brv/ lives, not the linked workspace subdir.
      //
      // We verify this by checking that projectRoot takes priority over
      // worktreeRoot in the baseDir computation.
      const executor = new CurateExecutor()

      const createTaskSession = stub().resolves('session-1')
      const deleteTaskSession = stub().resolves()
      const executeOnSession = stub().resolves('curation complete')
      const agent = {
        cancel: stub().resolves(false),
        createTaskSession,
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession,
        execute: stub().resolves(''),
        executeOnSession,
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession: stub(),
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      // Execute with both projectRoot and worktreeRoot provided.
      // projectRoot is where .brv/ lives, worktreeRoot is a linked subdir.
      // Post-processing should use projectRoot, NOT worktreeRoot.
      const result = await executor.executeWithAgent(agent, {
        clientCwd: '/projects/monorepo/packages/api/src',
        content: 'test content for curation',
        projectRoot: '/projects/monorepo',
        taskId: 'task-ws-1',
        worktreeRoot: '/projects/monorepo/packages/api',
      })

      expect(result).to.equal('curation complete')
      // Verify the agent was called (session lifecycle is correct)
      expect(createTaskSession.calledOnce).to.be.true
      expect(deleteTaskSession.calledOnce).to.be.true
    })

    it('should fall back to clientCwd when projectRoot is not provided', async () => {
      const executor = new CurateExecutor()

      const agent = {
        cancel: stub().resolves(false),
        createTaskSession: stub().resolves('session-1'),
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession: stub().resolves(),
        execute: stub().resolves(''),
        executeOnSession: stub().resolves('done'),
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession: stub(),
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      // No projectRoot — should fall back to clientCwd for baseDir
      const result = await executor.executeWithAgent(agent, {
        clientCwd: '/projects/myapp',
        content: 'test',
        taskId: 'task-ws-2',
      })

      expect(result).to.equal('done')
    })
  })

  describe('summary cascade deferral to dream (ENG-2485)', () => {
    it('enqueues stale-summary paths to the dream queue and does NOT call propagateStaleness inline', async () => {
      const agent = {
        cancel: stub().resolves(false),
        createTaskSession: stub().resolves('session-id'),
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession: stub().resolves(),
        execute: stub().resolves(''),
        executeOnSession: stub().resolves('curated'),
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession: stub(),
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      // pre-state empty, post-state has one new file → diffStates yields one changed path
      stub(FileContextTreeSnapshotService.prototype, 'getCurrentState')
        .onFirstCall()
        .resolves(new Map())
        .onSecondCall()
        .resolves(new Map([['auth/jwt.md', {hash: 'h', size: 1}]]))
      const propagateStalenessStub = stub(
        FileContextTreeSummaryService.prototype,
        'propagateStaleness',
      ).resolves([])
      stub(FileContextTreeManifestService.prototype, 'buildManifest').resolves()
      const enqueueStub = stub(DreamStateService.prototype, 'enqueueStaleSummaryPaths').resolves()
      // incrementCurationCount is unrelated dream-state work that runs after the post-curation
      // step; stub it so the test doesn't hit disk for the dream state file.
      stub(DreamStateService.prototype, 'incrementCurationCount').resolves()

      const taskId = 'curate-op-uuid-1'
      const projectRoot = '/projects/myapp'
      const executor = new CurateExecutor()
      await executor.executeWithAgent(agent, {
        clientCwd: projectRoot,
        content: 'capture auth knowledge',
        projectRoot,
        taskId,
      })

      // ENG-2485 invariant: the LLM-bound propagateStaleness walk MUST NOT run
      // on the curate hot path. It is deferred to the next dream cycle.
      expect(propagateStalenessStub.called).to.equal(false)

      // The deferred work is captured in the dream queue: the changed paths from
      // diffStates are enqueued for the next dream cycle to drain.
      expect(enqueueStub.calledOnce).to.equal(true)
      expect(enqueueStub.firstCall.args[0]).to.deep.equal(['auth/jwt.md'])
    })
  })

  describe('pre-pipelined recon (ENG-2530)', () => {
    it('injects __recon_result_<taskIdSafe> as a sandbox variable and surfaces it in the prompt', async () => {
      const taskId = '7a2b9e10-cdef-4321-8765-0abcdef01234'
      const taskIdSafe = taskId.replaceAll('-', '_')
      const expectedReconVar = `__recon_result_${taskIdSafe}`

      const setSandboxVariableOnSession = stub()
      const executeOnSession = stub().resolves('ok')

      const agent = {
        cancel: stub().resolves(false),
        createTaskSession: stub().resolves('session-id'),
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession: stub().resolves(),
        execute: stub().resolves(''),
        executeOnSession,
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession,
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      // Stub the post-curate filesystem services so the test stays
      // fully in-memory (mirrors the ENG-2485 test above). Without
      // these, executeWithAgent attempts real I/O against /projects/myapp.
      stub(FileContextTreeSnapshotService.prototype, 'getCurrentState').resolves(new Map())
      stub(DreamStateService.prototype, 'incrementCurationCount').resolves()

      const executor = new CurateExecutor()
      await executor.executeWithAgent(agent, {
        clientCwd: '/projects/myapp',
        content: 'plain text content for the curate to inspect',
        taskId,
      })

      // (a) recon result was set on the task session under __recon_result_<taskIdSafe>
      const reconCall = setSandboxVariableOnSession
        .getCalls()
        .find((c) => c.args[1] === expectedReconVar)
      expect(reconCall, `no setSandboxVariableOnSession call with key ${expectedReconVar}`).to.not.equal(undefined)

      const reconValue = reconCall?.args[2] as Record<string, unknown> | undefined
      expect(reconValue).to.have.property('suggestedMode')
      expect(reconValue).to.have.property('suggestedChunkCount')
      expect(reconValue).to.have.property('meta')
      const meta = reconValue?.meta as Record<string, unknown>
      expect(meta).to.have.property('charCount')
      expect(meta).to.have.property('lineCount')
      expect(meta).to.have.property('messageCount')

      // (b) prompt instructs the agent that recon is pre-computed and to skip the call
      expect(executeOnSession.calledOnce).to.equal(true)
      const promptArg = executeOnSession.firstCall.args[1] as string
      expect(promptArg).to.include('Recon already computed in')
      expect(promptArg).to.include(expectedReconVar)
      expect(promptArg).to.include('Do NOT call tools.curation.recon')
    })
  })

  describe('runAgentBody / finalize split', () => {
    // runAgentBody must return the response BEFORE Phase 4 runs so the daemon
    // can fire `task:completed` early and queue finalize for background work.
    // Under cascade-defer (ENG-2485), Phase 4 is enqueueStaleSummaryPaths +
    // buildManifest — it must NEVER call propagateStaleness inline.

    it('returns the agent response without running Phase 4 first', async () => {
      const agent = buildSplitTestAgent()
      stub(FileContextTreeSnapshotService.prototype, 'getCurrentState')
        .onFirstCall()
        .resolves(new Map())
        .onSecondCall()
        .resolves(new Map([['auth/jwt.md', {hash: 'h', size: 1}]]))
      const propagateStalenessStub = stub(
        FileContextTreeSummaryService.prototype,
        'propagateStaleness',
      ).resolves([])
      const buildManifestStub = stub(FileContextTreeManifestService.prototype, 'buildManifest').resolves()
      const enqueueStub = stub(DreamStateService.prototype, 'enqueueStaleSummaryPaths').resolves()
      stub(DreamStateService.prototype, 'incrementCurationCount').resolves()

      const executor = new CurateExecutor()
      const {finalize, response} = await executor.runAgentBody(agent, {
        clientCwd: '/p',
        content: 'capture',
        projectRoot: '/p',
        taskId: 't1',
      })

      // Phase 4 must NOT have run yet — response was returned immediately.
      expect(response).to.equal('curated')
      expect(enqueueStub.called).to.be.false
      expect(buildManifestStub.called).to.be.false
      expect((agent.deleteTaskSession as ReturnType<typeof stub>).called).to.be.false

      // finalize() runs Phase 4: enqueue + manifest rebuild + session cleanup.
      // ENG-2485 invariant: propagateStaleness MUST NOT run on the curate path.
      await finalize()
      expect(enqueueStub.calledOnce).to.be.true
      expect(buildManifestStub.calledOnce).to.be.true
      expect(propagateStalenessStub.called).to.be.false
      expect((agent.deleteTaskSession as ReturnType<typeof stub>).calledOnce).to.be.true
    })

    it('cleans up the task session if the agent body throws (no finalize returned)', async () => {
      const agent = buildSplitTestAgent()
      ;(agent.executeOnSession as ReturnType<typeof stub>).rejects(new Error('agent failed'))

      const executor = new CurateExecutor()
      try {
        await executor.runAgentBody(agent, {clientCwd: '/p', content: 'x', taskId: 't2'})
        expect.fail('should have thrown')
      } catch (error) {
        expect((error as Error).message).to.equal('agent failed')
      }

      // Even on agent body failure, the session must be cleaned up — no leak.
      expect((agent.deleteTaskSession as ReturnType<typeof stub>).calledOnceWithExactly('session-id')).to.be.true
    })

    it('executeWithAgent (backwards-compat wrapper) still runs Phase 4 inline before returning', async () => {
      const agent = buildSplitTestAgent()
      stub(FileContextTreeSnapshotService.prototype, 'getCurrentState')
        .onFirstCall()
        .resolves(new Map())
        .onSecondCall()
        .resolves(new Map([['auth/jwt.md', {hash: 'h', size: 1}]]))
      stub(FileContextTreeSummaryService.prototype, 'propagateStaleness').resolves([])
      stub(FileContextTreeManifestService.prototype, 'buildManifest').resolves()
      const enqueueStub = stub(DreamStateService.prototype, 'enqueueStaleSummaryPaths').resolves()
      stub(DreamStateService.prototype, 'incrementCurationCount').resolves()

      const executor = new CurateExecutor()
      const result = await executor.executeWithAgent(agent, {
        clientCwd: '/p',
        content: 'x',
        projectRoot: '/p',
        taskId: 't3',
      })

      expect(result).to.equal('curated')
      // Wrapper awaits finalize internally — cascade-defer enqueue ran by the
      // time we get here.
      expect(enqueueStub.calledOnce).to.be.true
    })
  })
})
